---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:8000'
  
  - job_name: 'crawler'
    static_configs:
      - targets:
        - 'crawler:8000'

  - job_name: 'node'
    static_configs:
     - targets:
       - 'node-exporter:9100'